### ISSUE TITLE
Gem5 install error. scons build/ARM/gem5.opt

### ISSUE THREAD

**Issue by Liangxiangeng** [cirosantilli-work/issues#5]
OS：Linux redhat 6.8.
GCC：4.8.5
Python：2.7.8
Scons: 3.1.1
zlib: 1.2.3
m4:1.4.13
protobuf:2.5.0
pydot:1.4.1
When "scons build/ARM/gem5.opt" There are some errors
For example:
ext/pybind11/include/pybind11/pytypes.h:735:78: error: 'PyCapsule_CheckExact' was not declared in this scope
ext/pybind11/include/pybind11/pytypes.h:1100:88: error: 'PyCapsule_GetContext' was not declared in this scope
ext/pybind11/include/pybind11/pybind11.h:770:20: error: 'it' was not declared in this scope
Why there are so many not declared parts?
Thank you!

**Comment by cirosantilli2** [comment]
Sorry, I just found out I wasn't subscribed to this repo, what a fail.

If this is still a problem, could you please report it at: https://gem5.atlassian.net/projects/GEM5/issues as well, and leave a link to the issue here?

I've been testing on Ubuntu 19.10/18.04, but we definitely want RedHat to work as well.

Closing in favor of the future issue tracker issue.
