### ISSUE TITLE
gem5 KVM support for ARM with a GICv3-only host without GICv2

### ISSUE THREAD

**Issue by austinharris** [cirosantilli-work/issues#8]
Hello,

I was wondering what the current state of KVM support for armv8 looks like? 

I have been trying to run on a graviton2 instance and I made a little bit of progress by hard-coding `kvm_gicv2_class = Gic400` since the gicv2 device doesn't exist in this host (will this work?). 

However I get this output:

`
0: system.cpu_cluster.cpus: Entering KVM...
0: system.cpu_cluster.cpus: KVM: Executing for 18446744073709551615 ticks
0: global: Arming POSIX timer: 18446744073709551615 ticks`

I let it run for quite awhile and it never seemed to come back. Additionally when I hit ctrl-c it outputs:

`0: system.cpu_cluster.cpus: KVM: Executed 0 instructions in 352981159642 cycles`

So it seems like KVM isn't even executing any instructions?

Is the only way to get this working to add gic v3 support?

Thanks a lot!
Austin

**Comment by cirosantilli2** [comment]
Hi Austin,

Please don't open issues here in the future, this repo was only created before they finally accepted to create an official issue tracker for the project at: https://gem5.atlassian.net/browse/GEM5 , use that instead next time, I see all messages there, and sooner when they are marked with `arch-arm`.

About KVM, generally things are flaky because we are lacking the manpower/expertise to make it work amazingly, even though we would really like it to, and will review patches.

I don't fully understand things myself, but I'm certain it does not work out of box with a non-GICv2 host.

There are two options:

- KVM can be configured to use a software GICv2, i.e. simulated by gem5, but for reasons I don't fully understand (interaction with timers mostly), some patching is still needed. We know of one not-yet-public effort trying to make it work, but don't have any fixed timelines on it.
- implement GICv3 support as you said. This is likely the saner option, if you were to try something, I would just try that.

After that though, there are likely to be other bugs, e.g.: https://stackoverflow.com/questions/53523087/how-to-run-gem5-on-kvm-on-arm-with-multiple-cores

**Comment by austinharris** [comment]
Hi Ciro,

I also tried this out on a graviton (1st-gen) which supports the GiCv2 device and I had the same results. Do you happen to know of any configuration where KVM was working that could help me narrow down the issue, since it doesn't appear to be the GiC?

Thanks,
Austin

**Comment by austinharris** [comment]
https://gem5.atlassian.net/browse/GEM5-547 comment added to similar issue here.

Thanks a lot!
